### ISSUE TITLE
Add newsletter template

### ISSUE THREAD

**Issue by souravcipher** [openprivacytech/community#2]

**Comment by Neilblaze** [comment]
@souravcipher is this issue targeted for [**`openprivacytech.org`**](https://github.com/openprivacytech/openprivacytech.org)?

**Comment by souravcipher** [comment]
This is a community newsletter template where everyone can contribute to our GitHub repo.

It will be published on our website as well as via a mailing list.

**Comment by Harshit-Raj-14** [comment]
@souravcipher I would like to work in this. Can you please tell in brief how exactly can I do it.

**Comment by souravcipher** [comment]
Hi, you are welcome to improve the current templated that was merged recently! Thank you.
