### ISSUE TITLE
Write a README for the community repo

### ISSUE THREAD

**Issue by souravcipher** [openprivacytech/community#3]

**Comment by tripur3121** [comment]
Hey @souravcipher ! I am interested to contribute.
Can you point me to the starting point?

**Comment by souravcipher** [comment]
Hi @tripur3121, thanks for your interest in contributing. 

This is issue supposed to be part of the season of docs, but you can contribute.

**Comment by souravcipher** [comment]
Can you be a little specific about your questions?

**Comment by souravcipher** [comment]
I'm also thinking about updating the code of conduct to the latest version [v2.1](https://www.contributor-covenant.org/version/2/1/code_of_conduct/) 

You are welcome to contribute in this issue
https://github.com/openprivacytech/.github/issues/2

**Comment by tripur3121** [comment]
@souravcipher Thank you for replying and pointing me toward more issues.

**Comment by tripur3121** [comment]
> Hi @tripur3121, thanks for your interest in contributing.
> 
> This is issue supposed to be part of the season of docs, but you can contribute.

My question is, "Write a README for the community repository." What exactly are you looking for, such as where to begin and what to include in the repository? Could point me toward some resources or points?

#### And I'm keen on joining the openprivacytech as a technical writer for the season of docs

**Comment by tripur3121** [comment]
@souravcipher My question is, "Write a README for the community repository." What exactly are you looking for, such as where to begin and what to include in the repository? Could point me toward some resources or points?

**Comment by souravcipher** [comment]
Thanks Tripur for the question, I'll get back to you soon.

**Comment by souravcipher** [comment]
Hi, if you are still interest on this issue

take a look at the current README and improve the content. 

There are three things I'm looking for -
1. Adding badges
2. Adding a table of content
3. Improving the content

Closing this issue for now.

**Comment by souravcipher** [comment]
![image](https://user-images.githubusercontent.com/72210541/228294887-f35d761d-83cf-430d-b8fc-b4ee3fb5790b.png)

badges or something like this.
